name: snowflake-pytest-poc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.3.1
  - pytest=6.2.5
  - pytest-bdd=3.2.1
  - pytest-xdist=2.4.0
  - pip:
      - snowflake-connector-python[pandas]==2.7.1
      - snowflake-sqlalchemy==1.3.2
      - SQLAlchemy==1.4.27
